FILE = *.cpp

CC = g++ -std=c++11

INCLUDE_PATHS = -I/usr/local/include 

COMPILER_FLAGS = -Wall

LINKER_FLAGS = -lglfw

NAME = main.exe

all: $(FILE)
	$(CC) $(FILE) $(INCLUDE_PATHS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(NAME)